hub: hub
maps:
- sab1
- sab2
- sab3
items:
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: BOW
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: ARROW
        amount: 32
        
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: STONE_SWORD
    
    
-   weight: 10.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: WOODEN_SWORD
    
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: LEATHER_HELMET
    
-   weight: 2.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: LEATHER_CHESTPLATE
    
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: LEATHER_LEGGINGS
    
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: LEATHER_BOOTS
    
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: GOLDEN_HELMET
    
-   weight: 1.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: GOLDEN_CHESTPLATE
    
-   weight: 2.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: GOLDEN_LEGGINGS
        
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: GOLDEN_BOOTS
    
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: FISHING_ROD
    
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: POTION
        meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '"Potion of Fire Resistance"'
            potion-type: minecraft:water
            custom-effects:
            -   ==: PotionEffect
                effect: 12
                duration: 1200
                amplifier: 0
                ambient: false
                has-particles: true
                has-icon: true
        
-   weight: 1.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: POTION
        meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '"Potion of Regeneration"'
            potion-type: minecraft:water
            custom-effects:
            -   ==: PotionEffect
                effect: 10
                duration: 1200
                amplifier: 0
                ambient: false
                has-particles: true
                has-icon: true
        
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: POTION
        meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '"Potion of Swiftness"'
            potion-type: minecraft:water
            custom-effects:
            -   ==: PotionEffect
                effect: 1
                duration: 1200
                amplifier: 0
                ambient: false
                has-particles: true
                has-icon: true
        
special_items:
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: IRON_SWORD
        
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: IRON_HELMET
        
-   weight: 10.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: IRON_CHESTPLATE
    
-   weight: 5.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: IRON_LEGGINGS
    
-   weight: 2.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: IRON_BOOTS
    
-   weight: 3.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: TNT
        amount: 5
        
-   weight: 7.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: CROSSBOW
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: ARROW
        amount: 32
        
-   weight: 1.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: POTION
        meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '"Potion of Leaping"'
            potion-type: minecraft:water
            custom-effects:
            -   ==: PotionEffect
                effect: 8
                duration: 1200
                amplifier: 1
                ambient: false
                has-particles: true
                has-icon: true
                
-   weight: 1.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: POTION
        meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '"Potion of Regeneration"'
            potion-type: minecraft:water
            custom-effects:
            -   ==: PotionEffect
                effect: 10
                duration: 1200
                amplifier: 1
                ambient: false
                has-particles: true
                has-icon: true
            
-   weight: 1.0
    items:
    -   ==: org.bukkit.inventory.ItemStack
        v: 3105
        type: POTION
        meta:
            ==: ItemMeta
            meta-type: POTION
            display-name: '"Potion of Swiftness"'
            potion-type: minecraft:water
            custom-effects:
            -   ==: PotionEffect
                effect: 1
                duration: 1200
                amplifier: 1
                ambient: false
                has-particles: true
                has-icon: true
detective:
    detective: 0
    innocent: -50
    saboteur: 40
    death: 0
innocent:
    detective: -75
    innocent: -50
    saboteur: 40
    death: 0
saboteur:
    detective: 40
    innocent: 25
    saboteur: -75
    death: -20
lobby:
    hours: 0
    minutes: 1
    seconds: 30
    reload: 0
tester:
    hours: 0
    minutes: 0
    seconds: 15
    reload: 3
refill:
    hours: 0
    minutes: 5
    seconds: 0
    reload: 0
ingame:
    hours: 0
    minutes: 10
    seconds: 0
    reload: 0
panic_life:
    hours: 0
    minutes: 0
    seconds: 3
    reload: 0
collection:
    hours: 0
    minutes: 0
    seconds: 15
    reload: 0
corpse_tester:
    hours: 0
    minutes: 0
    seconds: 10
    reload: 0
mirror_illusion:
    hours: 0
    minutes: 0
    seconds: 30
    reload: 0
test_corpse_range: 10
max_panic_blocks: 5
karma_ban_threshold: 0
karma_ban_command: "ban %player% Karma threshold reached 1w"