name: Sabotage
main: ml.sabotage.Main
version: 1.0.0
api-version: 1.19
author: "0-o#9646"

softdepend: [PlaceholderAPI]
depend: [Config, CorpseImmortal]

commands:
    sabotage:
        aliases: [sab]
        description: Generic plugin command.
        permission: zerodasho.sabotage.generic
    sabmap:
        permission: zerodasho.sabotage.sabmap
    vote:
        description: Vote for maps in the pregame lobby.
        permission: zerodasho.sabotage.vote
    shop:
        description: Buy in-game shop items.
        permission: zerodasho.sabotage.shop
        
permissions:
    zerodasho.sabotage.sabmap:
        default: op
    zerodasho.sabotage.vote:
        default: true
    zerodasho.sabotage.shop:
        default: true
    zerodasho.sabotage.attributes.nohunger:
        default: true
    zerodasho.sabotage.attributes.nodamage:
        default: true
    zerodasho.sabotage.attributes.generic:
        default: true
